kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kstar-planner-vol
spec:
  storageClassName: nfs-filestorage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
